paths:
  /store/add:
    post:
      tags:
        - Store
      summary: 가게추가
      parameters:
        - name: add
          in: body
          re-quired: true
          schema:
            properties:
              name:
                type: string
                description: 가게이름
                example: 호랑이커피
              address:
                type: string
                description: 가게주소
                example: address, asdfe a dsaf
              region_id:
                type: int
                description: 지역 아이디
                example: 1
      responses:
        "200":
          description: 가게 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: 2000
              message:
                type: string
                example: "sucess!"
              data:
                type: object
                example: {}

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다
